### ISSUE TITLE
Center up game

### ISSUE THREAD

**Issue by d4rkd0s** [d4rkd0s/bob#6]
Make the game centered on page

**Comment by airinhowl** [comment]
or bigger would be good. I know it goes full screen though.

**Comment by d4rkd0s** [comment]
@airinhowl I could make it simply "Full-width" that might be good. I'm going to start with matching the title screen which is centered nicely now. 

![Image of screen](https://i.imgur.com/hszhokQ.png)

**Comment by d4rkd0s** [comment]
All set!
